### ISSUE TITLE
Fails in python3 works in python2

### ISSUE THREAD

**Issue by sammypanda** [zb3/gnome-gamma-tool#10]
thank you, this is a life saver.. just noting here that it doesn't appear to work in python 3.7.5

```
  File "./gnome-gamma-tool.py", line 73
    if fit and (maxval := max(val)) > 1:  # the walrus operator says hello
                       ^
SyntaxError: invalid syntax
```

(works for me in python 2.7.18)

**Comment by zb3** [comment]
Yeah, the walrus operator was added in Python 3.8. While the reason for you using this old version of python is not my business, the only solution is a workaround in this case, as this is not a bug in ggt.

Try changing:
```python
    if fit and (maxval := max(val)) > 1:  # the walrus operator says hello
        val = list(map(lambda x: x / maxval, val))
```

to

```python
    if fit:
        maxval = max(val)
        if maxval > 1:
            val = list(map(lambda x: x / maxval, val))
```

**Comment by sammypanda** [comment]
solved, could maybe have python3 requirement added to readme
