### ISSUE TITLE
Applied profiles do not change gamma

### ISSUE THREAD

**Issue by Milliw** [zb3/gnome-gamma-tool#12]
Tried for both of my displays. Profile does get applied as I can tell by checking in Gnome settings but it does not change gamma at all.

I guess it's due to Nvidia drivers not allowing gamma change on Wayland - but I do not know for sure as I have only read that information online. If so, it should be mentioned in the readme.

Regards =)

**Comment by zb3** [comment]
@Milliw take a look at https://github.com/zb3/gnome-gamma-tool/issues/11
Which versions are you using?

**Comment by Milliw** [comment]
> @Milliw take a look at #11 Which versions are you using?

Gnome 43.2, Nobara 37, Kernel 6.2.14-300.fsync.fc37.x86_64 x86_64
If that is, what you've asked for. Not sure though.

Read that #11 issue.

**Comment by zb3** [comment]
@Milliw did it work before? That issue mentions that the solution was to upgrade the kernel, but he also used nvidia.

So logically it shouldn't be that nvidia somehow prevents the gamma from being changed on Wayland, because that user got it to work

**Comment by Milliw** [comment]
Don't know, what you mean by "before".
I tried to use this script for the first time.

There does not seem to be an upgrade to kernel 6.3 available for Nobara yet.

**Comment by zb3** [comment]
Ok, I didn't know that. But like I said, I can't say that it doesn't work with NVIDIA at all, because that user says it does. I can keep this issue open though.

**Comment by Milliw** [comment]
Hey there. Just want to report back. Meanwhile 6.3 kernel arrived on Nobara but I also changed to AMD graphics card at the same time. So I can only report back, that it is working now. Sorry to not beeing able to report something more useful but it was really by accident having both changes at the same time...

Nevertheless I want to thank you again for this really handy tool! =)
