### ISSUE TITLE
Profile disappear after logout

### ISSUE THREAD

**Issue by domryba** [zb3/gnome-gamma-tool#15]
gnome-gamma-tool creates and applies profiles correctly, but when I logout, they disappear on GNOME settings app.

```
./gnome-gamma-tool.py -g 0.8
Current profile is /home/dom/.local/share/icc/edid-75c94e30cdd9a420ea7870abb5a85f5d.icc
New profile is /home/dom/.local/share/icc/gnome-gamma-tool-697e2bda-871c-41d7-90c5-262aa4f67dca
Traceback (most recent call last):
  File "/home/dom/gnome-gamma-tool/./gnome-gamma-tool.py", line 398, in <module>
    main()
  File "/home/dom/gnome-gamma-tool/./gnome-gamma-tool.py", line 384, in main
    mgr.make_profile_default(new_profile)
  File "/home/dom/gnome-gamma-tool/./gnome-gamma-tool.py", line 316, in make_profile_default
    self.cdd.make_profile_default_sync(profile)
gi.repository.GLib.GError: cd_device_error: SQL error: attempt to write a readonly database (9)
```

**Comment by zb3** [comment]
Thanks for using gnome-gamma-tool and reporting the issue :)

Now, I'd need a bit more info about your system. It looks like colord can't write to its database but now I'd need to find out why.

First, please show me the output of
```
ps aux | grep colord
```
so I can know whether colord is running. It should run as the user `colord`.

Then I'd also need the output of:
```
sudo ls -l /proc/`pidof colord`/fd
```
(you should see a file named `storage.db` somewhere, in my case it resides in `/var/lib/colord/storage.db`)

Finally, the `storage.db` file should be writable by colord, you can check it with `stat`:
```
stat /var/lib/colord/storage.db
```

If everything is correct, perhaps the db is corrupt or something? Maybe there are some messages in the system log, check them with these commands:
```
journalctl -u colord
journalctl -b -g colord
```

So, even though it looks like you have some colord issue, if you provide more information I'll still try to help :)

**Comment by zb3** [comment]
No to wygląda na to, że `/var` faktycznie jest tylko do odczytu.. tą hipotezę możemy potwierdzić wynikiem komendy:
```
cat /proc/`pidof colord`/mountinfo
```

Może to wynika z jakiegoś błędu w systemie plików? System jest sprawdzony przez fsck?

**Comment by zb3** [comment]
Wydaje mi się, że to może mieć związek z ustawieniem `ProtectSystem=strict` wprowadzonym w tym commicie:
https://github.com/hughsie/colord/commit/d7352455075f6a6eb32e7d256dadb436cbd15ae8

Jeśli miałbyś chwilę to możesz spróbować zrobić upgrade a potem `sudo systemctl edit colord.service` i usunąć tą linię.. 
Wychodzi na to, że nikt tego nie testował XD
