### ISSUE TITLE
Feature Request: Change Red/Blue/Green

### ISSUE THREAD

**Issue by glidingthrough** [zb3/gnome-gamma-tool#16]
I have a weird problem on a secondhand laptop running Fedora Silverblue: GNOME is very blue.

I run the same OS on my other device and it's fine, so it's probably a fault with the monitor or a kernel/driver issue. Regardless of the cause, I was wondering if it might be possible to add the feature of changing the RBG values on the GNOME colour profile?

Reducing the gamma with this script has helped a bit, so I thank you for that :) Having this additional feature would help me shift it back to a more normal colour balance.

**Comment by zb3** [comment]
Hi, I think this is already possible (unless your it's your monitor that adds a constant value to the blue channel), because both gamma and contrast settings work per-channel!

Here's how to make the screen less blue by multiplying the channel:
```
./gnome-gamma-tool.py -c 1:1:0.5
```

Does that work?
