### ISSUE TITLE
Required package for OpenSUSE Tumbleweed

### ISSUE THREAD

**Issue by woiwoiwoiwoi** [zb3/gnome-gamma-tool#25]
I just used this on OpenSUSE Tumbleweed to change the colours on one of my two screens. Works well, thank you!

Just wanted to leave the info here that the required package on Tumbleweed is `typelib-1_0-Colord-1_0`. Maybe you could also add this to your readme for future users.

Thanks again!

**Comment by zb3** [comment]
Thanks for reporting this!
I've added this info :)
(feel free to reopen if I missed something..)
