### ISSUE TITLE
Feature Request: Change Saturation

### ISSUE THREAD

**Issue by nxs-neo** [zb3/gnome-gamma-tool#26]
Is there any way to increase or decrease saturation on gnome wayland?

**Comment by zb3** [comment]
This cannot be acheved with 1D lut (we need to know all 3 color channels r, g, b) to adjust each and VCGT doesn't provide a way to do this.

Closing as duplicate of https://github.com/zb3/gnome-gamma-tool/issues/9

**Comment by zb3** [comment]
3 years late, but.. I've created a GNOME extension that can do this, however, it has some limitations:
https://github.com/zb3/gnome-saturation-extension

**Comment by nxs-neo** [comment]
This is almost exactly what I was looking for. Just to slightly increase the saturation. Thank you
