### ISSUE TITLE
Feature request: Vibrance/Saturation

### ISSUE THREAD

**Issue by CapSel** [zb3/gnome-gamma-tool#6]
Could you add feature that vibrantLinux (https://github.com/libvibrant/vibrantLinux)?

**Comment by zb3** [comment]
Unless I'm missing something, that's not possible due to the way VCGT table works because in that table, the output of a given channel (R, G, B) depends only on the input of the same channel, so transforms where the output value depends on all channels are out of the question.

**Comment by CapSel** [comment]
No... you're not missing anything. Thanks.
